### ISSUE TITLE
Why is there an 'r' before some docstrings?

### ISSUE THREAD

**Issue by ReblochonMasque** [slightlynybbled/tk_tools#27]
I noticed some docstrings start with an `r` prior to the triple quotes; what is the reason?

```
class Widget:  
    r"""a class to represent widgets
    """
```

**Comment by slightlynybbled** [comment]
There were some packages that worked better at one time with `r`aw strings.  I no longer believe that is the case, so I am generally removing the `r` in most places, but I'm not doing it proactively.

**Comment by ReblochonMasque** [comment]
Noted, thank you.
This issue can be closed, or marked '_easy first contribution'_, if you want to, maybe, attract contributors.
