### ISSUE TITLE
Calendar translations

### ISSUE THREAD

**Issue by maicol07** [slightlynybbled/tk_tools#31]
Hi,
is it possible to translate in different languages the Calendar widget? For exxample, months and days, that are displayed in the Calendar.
Thanks

**Comment by slightlynybbled** [comment]
I'm sure that is is possible, but I have no idea how this might be approached within tkinter.  Will tag this as 'help wanted'.

**Comment by maicol07** [comment]
How text is displayed? With labels?

**Comment by ReblochonMasque** [comment]
You might want to look at the local constants accessed by python - I think there is a module in the standard lib that allows to use the system locals, for time, date, and language settings.

**Comment by ReblochonMasque** [comment]
Here is an approach to set the `locale`:

https://stackoverflow.com/questions/985505/locale-date-formatting-in-python
https://stackoverflow.com/questions/955986/what-is-the-correct-way-to-set-pythons-locale-on-windows/956084#956084

**Comment by AokiAhishatsu** [comment]
I can confim this is working on Windows (10):

`locale.setlocale(locale.LC_ALL, 'deu_deu')`

_Calendar is shown in german language as expected_

**Comment by slightlynybbled** [comment]
@AokiAhishatsu So does that mean that this is already addressed and there is no need to do anything or is there something that needs to be modified within the package?

**Comment by ReblochonMasque** [comment]
Thanks for the confirmation @AokiAhishatsu.
I agree, the code does not need modification; a nice explanation on how to do this would be welcomed though. The docstring is probably the best place for it.

**Comment by slightlynybbled** [comment]
This has been addressed with a more comprehensive example and a blurb within [the documentation](https://tk-tools.readthedocs.io/en/latest/widget_groups.html#calendar).
