### ISSUE TITLE
Add dependencies to readme and requirements

### ISSUE THREAD

**Issue by AokiAhishatsu** [slightlynybbled/tk_tools#32]
Since ef464f11b588a083139a6f3381dc16c78834fd24 there is [engineering-notation](https://pypi.org/project/engineering-notation/)
Are there any more?

**Comment by slightlynybbled** [comment]
I have a new feature on the horizon to read/write an excel sheet into/out of an entry which will require `xlrd` and `xlwt`, but I haven't fully implemented them yet.  Much of the code is present, but I haven't had the time to work on it.

**Comment by AokiAhishatsu** [comment]
Ok, looking forward to it.

A new PyPI would also be great, (no hurry if you got no time atm)

**Comment by slightlynybbled** [comment]
Agreed.  Just uploaded current code base to pypi.

**Comment by slightlynybbled** [comment]
Removed spreadsheet reader.  It is a bit of an overreach for a GUI package.  May implement at some future date as a separate module.  See 74ade6b

**Comment by slightlynybbled** [comment]
Added dependencies to readme, see 7c1792c
