### ISSUE TITLE
KeyValueEntry locks entries on load

### ISSUE THREAD

**Issue by slightlynybbled** [slightlynybbled/tk_tools#40]
The default behavior should be based on the enabled state of the block before the load.

**Comment by jamesagada** [comment]
Is it possible to change the state after? After loading, can we change the enabled status?

**Comment by slightlynybbled** [comment]
I fixed this in v0.12.0.  If an entry was enabled before it was loaded, it will again be enabled.  If it was disabled before it was loaded, it will be disabled.  This was the desired behavior from the start, but now it is fixed.

    python -m pip install --upgrade tk-tools

Yes, you can change the enabled state at any time.  Use the `change_enables` method.
