### ISSUE TITLE
disable smart option menu?

### ISSUE THREAD

**Issue by ghost** [slightlynybbled/tk_tools#47]
I am using tk-tools for first time and I am trying to temporarily
disable the smart option menu and re-enable later.

I used this I found in the docs:

tk_tools.enable=False

which doesn't seem to work, I can find no way
of refreshing the widget either, 

working on the assigned name of the widget (drop_down in my case)
doesn't work either, causes an error.

Any ideas?

**Comment by slightlynybbled** [comment]
Greetings -

There is no way to disable the `SmartOptionMenu` at this time.  The blurb that you posted must have been from a different section of the documentation or, perhaps, got confused with a different library as I can find no reference to that particular like.  My recommendation would be to write your own `OptionMenu` variant which implements the exact behavior that you require.  Good luck!

j

**Comment by ghost** [comment]
OK thank you, fair enough, the smart option menu is awesome btw thank you for this great library.
Yes I did get the enable option from elsewhere in the docs, should have said that, I just hoped it would work,
as it didn't throw an error I thought I was onto something, no worries.
I don't think I have the competence yet to edit your SOM code but I will have a try.
